// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB'].toString(),
    appId: dotenv.env['FIREBASE_APP_ID_WEB'].toString(),
    messagingSenderId:
        dotenv.env['FIREBASE_MESSAGING_SENDER_ID_WEB'].toString(),
    projectId: dotenv.env['FIREBASE_PROJECT_ID_WEB'].toString(),
    authDomain: 'money-report-c87e7.firebaseapp.com',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET_WEB'].toString(),
    measurementId: dotenv.env['FIREBASE_MEASUREMENT_ID_WEB'].toString(),
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID'].toString(),
    appId: dotenv.env['FIREBASE_APP_ID_ANDROID'].toString(),
    messagingSenderId:
        dotenv.env['FIREBASE_MESSAGING_SENDER_ID_ANDROID'].toString(),
    projectId: dotenv.env['FIREBASE_PROJECT_ID_ANDROID'].toString(),
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET_ANDROID'].toString(),
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'].toString(),
    appId: dotenv.env['FIREBASE_APP_ID_IOS'].toString(),
    messagingSenderId:
        dotenv.env['FIREBASE_MESSAGING_SENDER_ID_IOS'].toString(),
    projectId: dotenv.env['FIREBASE_PROJECT_ID_IOS'].toString(),
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET_IOS'].toString(),
    iosClientId: dotenv.env['FIREBASE_IOS_CLIENT_ID_IOS'].toString(),
    iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID_IOS'].toString(),
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_MACOS'].toString(),
    appId: dotenv.env['FIREBASE_APP_ID_MACOS'].toString(),
    messagingSenderId:
        dotenv.env['FIREBASE_MESSAGING_SENDER_ID_MACOS'].toString(),
    projectId: dotenv.env['FIREBASE_PROJECT_ID_MACOS'].toString(),
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET_MACOS'].toString(),
    iosClientId: dotenv.env['FIREBASE_IOS_CLIENT_ID_MACOS'].toString(),
    iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID_MACOS'].toString(),
  );
}
